services:
  bot:
    build: .
    container_name: youtomp3-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
      - ./data:/app/data
      - ./app:/app/app
      - ./main.py:/app/main.py
